package com.mainProject;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;


/**
 *
 * @author Bharath Kumar Reddy Vatrapu
 */
        public class Help extends JFrame {

        /**
         * Creates new form Help
         */
        public Help() {
        initComponents();
        inint();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

        panelHelp = new JPanel();
        imgUserguideWord = new JLabel();
        txtUserGuide = new JLabel();
        btnMinimize = new JButton();
        btnClose = new JButton();

            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            setResizable(false);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            //setLocationRelativeTo(null);
            setUndecorated(true);

        panelHelp.setBackground(new java.awt.Color(GlobalConstants.side_Color_r,GlobalConstants.side_Color_g,GlobalConstants.side_Color_b));

        imgUserguideWord.setIcon(new ImageIcon(getClass().getResource("/icons/Microsoft_PowerPoint_100px.png")));
                imgUserguideWord.addMouseListener(new MouseAdapter() {
                        public void mouseClicked(MouseEvent e) {
                                imgUserguideWordActionPerformed();
                        }
                });
        txtUserGuide.setText("Dom Extractor User Guide");

        btnMinimize.setBackground(new java.awt.Color(GlobalConstants.body_Color_r,GlobalConstants.body_Color_g,GlobalConstants.body_Color_b));
        btnMinimize.setIcon(new ImageIcon(getClass().getResource("/icons/Subtract_20px.png")));
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setFocusPainted(false);
                btnMinimize.setVisible(false);

        btnClose.setBackground(new java.awt.Color(GlobalConstants.body_Color_r,GlobalConstants.body_Color_g,GlobalConstants.body_Color_b));
        btnClose.setIcon(new ImageIcon(getClass().getResource("/icons/Delete_20px.png")));
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setFocusPainted(false);
                btnClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClosesActionPerformed(evt);
                        }
                });

        GroupLayout panelHelpLayout = new GroupLayout(panelHelp);
        panelHelp.setLayout(panelHelpLayout);
        panelHelpLayout.setHorizontalGroup(
        panelHelpLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(panelHelpLayout.createSequentialGroup()
        .addGap(107, 107, 107)
        .addComponent(imgUserguideWord)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(GroupLayout.Alignment.TRAILING, panelHelpLayout.createSequentialGroup()
        .addContainerGap(97, Short.MAX_VALUE)
        .addComponent(txtUserGuide)
        .addGap(90, 90, 90))
        .addGroup(GroupLayout.Alignment.TRAILING, panelHelpLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(btnMinimize)
        .addGap(18, 18, 18)
        .addComponent(btnClose))
        );
        panelHelpLayout.setVerticalGroup(
        panelHelpLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(GroupLayout.Alignment.TRAILING, panelHelpLayout.createSequentialGroup()
        .addGroup(panelHelpLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addComponent(btnClose)
        .addComponent(btnMinimize))
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
        .addComponent(txtUserGuide)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(imgUserguideWord)
        .addGap(37, 37, 37))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addComponent(panelHelp, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addComponent(panelHelp, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

            pack();
            setLocationRelativeTo(null);
            setVisible(true);
        }
        private void btnClosesActionPerformed(java.awt.event.ActionEvent evt) {
                setVisible(false);
                dispose();
                GlobalConstants.Help_frame_visibility=false;

        }
        public void imgUserguideWordActionPerformed(){
                openHelpDoc();

        }
        public void openHelpDoc(){
                File file = new File(System.getProperty("user.dir")+File.separator+"src"+File.separator+"main"+File.separator+"resources"+File.separator+"doc"+File.separator+"help.ppt");
                try {
                        if (Desktop.isDesktopSupported()) {
                                Desktop.getDesktop().open(file);
                        }
                } catch (IOException ioe) {
                        ioe.printStackTrace();
                }
                JOptionPane.showMessageDialog(null, "Help Document is opening..", "Info" , JOptionPane.INFORMATION_MESSAGE);
        }
        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
               /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new Help().setVisible(true);
        }
        });
        }

        public void inint(){
                if(isVisible()){
                        GlobalConstants.Help_frame_visibility =true;
                }
        }

        // Variables declaration - do not modify
        private JButton btnClose;
        private JButton btnMinimize;
        private JLabel imgUserguideWord;
        private JPanel panelHelp;
        private JLabel txtUserGuide;
        // End of variables declaration
        }
